// Hand-chosen glosses, for the words where no automatic ranking can be trusted.
//
// build/senses.mjs ranks a lemma's dictionary senses by what the translators of
// 378,000 sentences actually reach for. That is right for most nouns,
// adjectives and verbs. It is wrong for two kinds of word: the closed class
// whose meaning IS a grammatical job (de, en, pas, plus, là — where Wiktionary's
// gloss is a paragraph), and the polysemous everyday verbs where the sense
// translators reach for is not the sense a learner should meet FIRST
// (passer is "to pass" before it is "to happen"; emmener is "to take along").
//
// So a person chose — by reading the first 1,000 words. build/verify.mjs fails
// the build if a choice here is not backed by Wiktionary: `from` must appear
// inside a gloss Wiktionary gives that lemma and kind. A hand-choice may
// RE-ORDER and COMBINE what the sources say; it may never add to it.
//
// key:   'lemma|kind'  (kind: n v adj adv prep conj int)
// g:     what the buttons show
// from:  a fragment of the Wiktionary gloss that backs it
// d:     the form shown, where the lemma is only ever used pronominally
// pick:  which kind wins when the spelling is more than one (nouveau: adj, not n)

export default {
  // — the verbs everything leans on —
  'être|v': { g: 'to be', from: 'to be' },
  'avoir|v': { g: 'to have', from: 'to have' },
  'faire|v': { g: 'to do; to make', from: 'to do' },
  'aller|v': { g: 'to go', from: 'to go' },
  'pouvoir|v': { g: 'can; to be able to', from: 'to be able to' },
  'vouloir|v': { g: 'to want', from: 'to want' },
  'devoir|v': { g: 'must; to have to', from: 'must' },
  'falloir|v': { g: 'to be necessary', from: 'to be necessary' },
  'savoir|v': { g: 'to know (a fact)', from: 'to know' },
  'connaître|v': { g: 'to know (a person or place)', from: 'to know' },
  'passer|v': { g: 'to pass; to spend (time)', from: 'to spend (time)' },
  'arriver|v': { g: 'to arrive; to happen', from: 'to arrive' },
  'aimer|v': { g: 'to like; to love', from: 'to love' },
  'emmener|v': { g: 'to take (someone) along', from: 'to take (someone) along' },
  'emporter|v': { g: 'to take away', from: 'to take away' },
  'apporter|v': { g: 'to bring', from: 'to bring' },
  'essayer|v': { g: 'to try', from: 'to try, to attempt' },
  'voler|v': { g: 'to fly; to steal', from: 'to steal' },
  'tenir|v': { g: 'to hold; to keep', from: 'to hold' },
  'rendre|v': { g: 'to give back; to make', from: 'to give back' },
  'tirer|v': { g: 'to pull; to shoot', from: 'to shoot' },
  'pousser|v': { g: 'to push; to grow', from: 'to push' },
  'porter|v': { g: 'to wear; to carry', from: 'to wear' },
  'retrouver|v': { g: 'to find again; to meet up', from: 'to meet' },
  'rappeler|v': { g: 'to call back; to remind', from: 'to remind' },
  'poser|v': { g: 'to put down; to ask (a question)', from: 'to ask or pose' },
  'coucher|v': { g: 'to put to bed; to sleep', from: 'to go to bed' },
  'reconnaître|v': { g: 'to recognize; to admit', from: 'to admit' },
  'occuper|v': { g: 'to occupy; to take care of', from: 'to occupy' },
  'asseoir|v': { g: 'to sit down', from: 'to sit down', d: 'asseoir (s’)' },
  'souvenir|v': { g: 'to remember', from: 'to remember', d: 'souvenir (se)' },
  'enfuir|v': { g: 'to run away', from: 'to escape', d: 'enfuir (s’)' },
  'méfier|v': { g: 'to be wary of', from: 'wary', d: 'méfier (se)' },

  // — nouns —
  'coup|n': { g: 'blow; shot; go', from: 'shot' },
  'salut|n': { g: 'salvation', from: 'salvation' },
  'chambre|n': { g: 'bedroom; room', from: 'a bedroom' },
  'cheveu|n': { g: 'hair (a single hair)', from: 'headhair' },
  'esprit|n': { g: 'mind; spirit', from: 'mind' },
  'gens|n': { g: 'people', from: 'set of people' },
  'pays|n': { g: 'country', from: 'country' },
  'peine|n': { g: 'sorrow; trouble; penalty', from: 'psychological pain, sorrow' },
  'pièce|n': { g: 'room; piece; coin', from: 'room in a house' },
  'suite|n': { g: 'what follows; sequel', from: 'sequel' },
  'tour|n': { g: 'turn; tower; tour', from: 'tower' },
  'truc|n': { g: 'thing; gadget; trick', from: 'thingamajig' },
  'envie|n': { g: 'desire; craving', from: 'appetite, craving' },
  'docteur|n': { g: 'doctor', from: 'doctor' },
  'bruit|n': { g: 'noise', from: 'noise' },
  'argent|n': { g: 'money', from: 'money' },

  // — adjectives —
  'nouveau|adj': { g: 'new', from: 'new', pick: true },
  'cher|adj': { g: 'expensive; dear', from: 'expensive' },
  'propre|adj': { g: 'clean; own', from: 'clean' },
  'tout|adj': { g: 'all; every', from: 'all' },
  'même|adj': { g: 'same', from: 'same' },
  'seul|adj': { g: 'alone; only', from: 'alone' },
  'noir|adj': { g: 'black', from: 'black' },
  'blanc|adj': { g: 'white', from: 'white' },
  'plein|adj': { g: 'full', from: 'full' },
  'juste|adj': { g: 'fair; right; tight', from: 'fair, just' },

  // — adverbs, prepositions, conjunctions, interjections —
  'de|prep': { g: 'of; from', from: 'from' },
  'en|prep': { g: 'in; to; by', from: 'in' },
  'dans|prep': { g: 'in; inside', from: 'in, inside' },
  'à|prep': { g: 'to; at', from: 'to' },
  'pour|prep': { g: 'for', from: 'for' },
  'avec|prep': { g: 'with', from: 'with' },
  'sans|prep': { g: 'without', from: 'without' },
  'sur|prep': { g: 'on', from: 'on' },
  'par|prep': { g: 'by; through', from: 'through' },
  'chez|prep': { g: 'at the home of', from: 'in or into the place of' },
  'pendant|prep': { g: 'during', from: 'during' },
  'selon|prep': { g: 'according to', from: 'according to' },
  'près|prep': { g: 'near', from: 'attached to' },
  'dès|prep': { g: 'from (a point in time)', from: 'from' },
  'voilà|prep': { g: 'there is; here is', from: 'it has been, ago' },
  'voici|prep': { g: 'here is; here are', from: 'ago' },
  'pas|adv': { g: 'not', from: 'not' },
  'plus|adv': { g: 'more', from: 'more' },
  'moins|adv': { g: 'less', from: 'minus' },
  'mieux|adv': { g: 'better', from: 'more, -er' },
  'là|adv': { g: 'there', from: 'there' },
  'si|adv': { g: 'so; if', from: 'so, such' },
  'puis|adv': { g: 'then; next', from: 'then; after; next', pick: true },
  'près|adv': { g: 'near', from: 'near' },
  'assez|adv': { g: 'enough; fairly', from: 'enough' },
  'combien|adv': { g: 'how much; how many', from: 'how much' },
  'plutôt|adv': { g: 'rather', from: 'rather' },
  'ensuite|adv': { g: 'then; next', from: 'then' },
  'cependant|adv': { g: 'however', from: 'however' },
  'dedans|adv': { g: 'inside', from: 'inward' },
  'autrefois|adv': { g: 'in the past', from: 'formerly' },
  'certainement|adv': { g: 'certainly', from: 'certainly' },
  'même|adv': { g: 'even', from: 'even' },
  'beaucoup|adv': { g: 'a lot; much', from: 'a lot' },
  'enfin|adv': { g: 'at last; finally', from: 'at last, finally' },
  'or|conj': { g: 'now; yet (in an argument)', from: 'yet' },
  'ni|conj': { g: 'neither; nor', from: 'neither' },
  'hé|int': { g: 'hey', from: 'hey' },
  'eh|int': { g: 'hey; eh', from: 'signifying indifference or surprise' },
  'tiens|int': { g: 'here you go; well, well', from: 'like, you know' },
  'allô|int': { g: 'hello (on the phone)', from: 'hello' },
  'euh|int': { g: 'um; er', from: 'um' },
  'merci|int': { g: 'thank you', from: 'thank' },
  'salut|int': { g: 'hi; bye (informal)', from: 'hi, hello', pick: true },
  // — the second pass: glosses that read as a paragraph, or the wrong sense —
  'tromper|v': { g: 'to deceive; to cheat on', from: 'to trick, dupe' },
  'gauche|n': { g: 'left (side)', from: 'the left, the left-hand side' },
  'droite|n': { g: 'right (side)', from: 'the right, right wing' },
  'présent|n': { g: 'present; gift', from: 'gift' },
  'crime|n': { g: 'crime', from: 'severe offences' },
  'lendemain|n': { g: 'the next day', from: 'the next day' },
  'mademoiselle|n': { g: 'Miss; young lady', from: 'young woman' },
  'lune|n': { g: 'moon', from: 'the Moon' },
  'public|adj': { g: 'public', from: 'of the people as a whole' },
  'veille|n': { g: 'the day before; eve', from: 'the day before, the eve' },
  'précis|adj': { g: 'precise', from: 'precise' },
  'masse|n': { g: 'mass; large amount', from: 'large amount or quantity' },
  'pire|n': { g: 'worse; the worst', from: 'the worst' },
  'rang|n': { g: 'row; rank', from: 'row or line' },
  'abri|n': { g: 'shelter', from: 'shelter' },
  'évoquer|v': { g: 'to evoke; to mention', from: 'to mention' },
  'fleuve|n': { g: 'river (flowing to the sea)', from: 'river that flows into an ocean' },
  'curé|n': { g: 'parish priest', from: 'priest bearing' },
  'reprocher|v': { g: 'to blame (someone for)', from: 'to blame' },
  'enregistrer|v': { g: 'to record', from: 'to record for later replay' },
  'gendarme|n': { g: 'gendarme; police officer', from: 'member of the gendarmerie' },
  'nuque|n': { g: 'nape of the neck', from: 'nape' },
  'langage|n': { g: 'language; speech', from: 'language: word choice' },
  'file|n': { g: 'line; queue', from: 'line of objects' },
  'bouleverser|v': { g: 'to upset; to turn upside down', from: 'to shake' },
  'écoute|n': { g: 'listening', from: 'listening in' },
  'quelconque|adj': { g: 'any; ordinary', from: 'any, any which one' },
  'blouse|n': { g: 'smock; blouse', from: 'uniform or coat' },
  'romain|adj': { g: 'Roman', from: 'of Ancient Rome' },
  'conscient|adj': { g: 'aware; conscious', from: 'aware of' },
  'plastique|n': { g: 'plastic', from: 'material that can be moulded' },
  'coupé|adj': { g: 'cut', from: 'divided into' },
  'aïe|int': { g: 'ouch', from: 'ouch' },
  'ho|int': { g: 'whoa; oh', from: 'surprise or shock' },
  'major|n': { g: 'major (military rank)', from: 'non-commissioned officer rank' },
  'engin|n': { g: 'machine; device', from: 'any device' },
  'navrer|v': { g: 'to upset; to sadden', from: 'to upset' },
  'divan|n': { g: 'couch', from: 'any type of undistinguished couch' },
  'conducteur|n': { g: 'driver', from: 'the driver of a vehicle' },
  'noix|n': { g: 'nut; walnut', from: 'any nut' },
  'cours|n': { g: 'class; lesson', from: 'lesson' },
  'hôtel|n': { g: 'hotel', from: 'hotel' },
  'réussir|v': { g: 'to succeed; to pass (an exam)', from: 'to manage to do something' },
  'plan|n': { g: 'plan; map', from: 'map' },
  'pardon|int': { g: 'sorry; pardon me', from: 'excuse me' },
  'avion|n': { g: 'airplane', from: 'aeroplane' },
  'blesser|v': { g: 'to wound; to hurt', from: 'to wound, to injure' },
  'bateau|n': { g: 'boat', from: 'vessel of any size' },
};
