// Notes on words that are easy to mix up — mostly the traps an English speaker
// falls into, because English and French share a great deal of vocabulary and
// not all of it means what it looks like it means.
//
// A note travels with every word it names (the word card shows it) and, where
// it has an `ask`, becomes a question of its own that asks the DISTINCTION
// rather than the gloss. A note whose words are not all in the deck is dropped
// by build/items.mjs rather than half-taught.
//
// The words and their glosses come from the sources. The advice about which to
// use when is mine, and the app says so wherever a note appears.
//
// `cues` — for a word whose gloss alone does not say which of two near-
// synonyms is wanted. A cue goes into "which one means …?" so the question has
// one right answer, not two.

export default [
  { id: 'actuellement', kind: 'false friend', words: ['actuellement', 'vraiment', 'autrefois', 'bientôt'],
    title: 'Actuellement is not “actually”',
    plain: 'Actuellement means “at the moment” or “currently”. For “actually”, French says en fait, or uses vraiment.',
    watch: 'It is among the most common slips of English speakers writing French, and it stays in the sentence unnoticed because it looks right.',
    ask: { prompt: 'Which one means “currently”?', answer: 'actuellement', with: ['vraiment', 'autrefois', 'bientôt'] },
    cues: { actuellement: 'at the moment, now', vraiment: 'truly, genuinely' } },
  { id: 'assister', kind: 'false friend', words: ['assister', 'aider', 'attendre', 'regarder'],
    title: 'Assister à is “to attend”',
    plain: 'Assister à une réunion is to attend a meeting. It is not “to assist”: for that, French says aider.',
    watch: 'And attendre, which looks as though it should mean “to attend”, means “to wait for”.',
    ask: { prompt: 'Which one means “to attend (a meeting or a show)”?', answer: 'assister', with: ['aider', 'attendre', 'regarder'] },
    cues: { assister: 'to attend an event' } },
  { id: 'attendre', kind: 'false friend', words: ['attendre', 'assister', 'entendre', 'attraper'],
    title: 'Attendre is “to wait”',
    plain: 'Attendre means to wait for. J’attends le bus: I am waiting for the bus. The word does not take a preposition for “for”.',
    watch: 'It also sits close to entendre (to hear) on the page, and the two are mistaken for each other in fast reading.',
    ask: { prompt: 'Which one means “to wait for”?', answer: 'attendre', with: ['assister', 'entendre', 'attraper'] } },
  { id: 'deception', kind: 'false friend', words: ['déception', 'surprise', 'erreur', 'peur'],
    title: 'Déception is “disappointment”',
    plain: 'A déception is a disappointment. French for “deception” is tromperie, and for “to deceive” it is tromper.',
    watch: 'The verb is décevoir, to disappoint.',
    ask: { prompt: 'Which one means “disappointment”?', answer: 'déception', with: ['surprise', 'erreur', 'peur'] } },
  { id: 'exiger', kind: 'false friend', words: ['exiger', 'demander', 'répondre', 'offrir'],
    title: 'Demander is “to ask”, not “to demand”',
    plain: 'Demander means to ask, politely and neutrally: je lui ai demandé de venir. To demand, French says exiger.',
    watch: 'Using demander where English has “demand” makes you sound far softer than you mean to be.',
    ask: { prompt: 'Which one means “to demand”?', answer: 'exiger', with: ['demander', 'répondre', 'offrir'] },
    cues: { exiger: 'to insist on', demander: 'to ask politely' } },
  { id: 'librairie', kind: 'false friend', words: ['bibliothèque', 'librairie', 'école', 'banque'],
    title: 'Librairie is a bookshop',
    plain: 'A librairie sells books. A bibliothèque is where you borrow them: a library.',
    watch: 'A bibliothèque is also a bookcase.',
    ask: { prompt: 'Which one means “a library”?', answer: 'bibliothèque', with: ['librairie', 'école', 'banque'] },
    cues: { bibliothèque: 'where you borrow books', librairie: 'where you buy books' } },
  { id: 'location', kind: 'false friend', words: ['location', 'lieu', 'endroit', 'place'],
    title: 'Location is “renting”',
    plain: 'Location is the act of renting something: une voiture de location, a rental car. For the place where something is, French says lieu or endroit.',
    watch: 'On a real-estate sign in Québec, à louer and à vendre are the pair: to rent and to sell.',
    ask: { prompt: 'Which one means “a rental”?', answer: 'location', with: ['lieu', 'endroit', 'place'] } },
  { id: 'sensible', kind: 'false friend', words: ['sensible', 'raisonnable', 'honnête', 'brave'],
    title: 'Sensible is “sensitive”',
    plain: 'Sensible means sensitive or easily affected, not sensible. For “sensible, reasonable”, French says raisonnable.',
    watch: 'Un enfant sensible is a sensitive child, not a sensible one.',
    ask: { prompt: 'Which one means “sensible, reasonable”?', answer: 'raisonnable', with: ['sensible', 'honnête', 'brave'] } },
  { id: 'supporter', kind: 'false friend', words: ['supporter', 'soutenir', 'attendre', 'tenir'],
    title: 'Supporter is “to put up with”',
    plain: 'Supporter means to bear or tolerate: je ne supporte pas le bruit. To support someone — to back them — French says soutenir.',
    watch: 'Un supporter is also a fan of a team. For backing someone’s idea or decision, soutenir is the careful choice.',
    ask: { prompt: 'Which one means “to support (back) someone”?', answer: 'soutenir', with: ['supporter', 'attendre', 'tenir'] },
    cues: { soutenir: 'to back someone', supporter: 'to put up with' } },
  { id: 'conference', kind: 'false friend', words: ['conférence', 'lecture', 'réunion', 'fête'],
    title: 'Conférence is a talk',
    plain: 'A conférence is a lecture or a talk given to an audience, and also a conference. Lecture is not a lecture: it means reading.',
    watch: 'It is lecture, with the same shape, that English speakers reach for.',
    ask: { prompt: 'Which one means “a talk given to an audience”?', answer: 'conférence', with: ['lecture', 'réunion', 'fête'] } },
  { id: 'reunion', kind: 'false friend', words: ['réunion', 'retour', 'conférence', 'fête'],
    title: 'Réunion is a meeting',
    plain: 'Une réunion is a meeting. A “reunion” of old friends is des retrouvailles.',
    watch: 'It is also the name of an island in the Indian Ocean.',
    ask: { prompt: 'Which one means “a (business) meeting”?', answer: 'réunion', with: ['retour', 'conférence', 'fête'] } },
  { id: 'delai', kind: 'false friend', words: ['délai', 'retard', 'départ', 'temps'],
    title: 'Délai is a time limit',
    plain: 'Un délai is the time allowed for something: dans un délai de trois jours, within three days. A delay — being late — is un retard.',
    watch: 'Respecter les délais is to meet the deadlines.',
    ask: { prompt: 'Which one means “a time limit, a deadline”?', answer: 'délai', with: ['retard', 'départ', 'temps'] },
    cues: { délai: 'time allowed', retard: 'being late' } },
  { id: 'stage', kind: 'false friend', words: ['stage', 'scène', 'étape', 'classe'],
    title: 'Un stage is an internship',
    plain: 'Un stage is a work placement or a training course: faire un stage, to do an internship. The stage of a theatre is la scène.',
    watch: 'A stagiaire is the intern.',
    ask: { prompt: 'Which one means “an internship, a work placement”?', answer: 'stage', with: ['scène', 'classe'] } },
  { id: 'large', kind: 'false friend', words: ['large', 'grand', 'long', 'haut'],
    title: 'Large is “wide”',
    plain: 'Large means wide. Something big overall is grand or gros; something wide is large: une rue large.',
    watch: 'Il est large d’épaules is broad-shouldered, and has nothing to do with being large in general.',
    ask: { prompt: 'Which one means “wide”?', answer: 'large', with: ['grand', 'long', 'haut'] } },
  { id: 'grand-gros', kind: 'near-synonyms', words: ['grand', 'gros', 'petit', 'jeune'],
    title: 'Grand and gros',
    plain: 'Grand is big in height or importance, and is what you say about a tall person. Gros is big in girth: thick, heavy, fat. A grand arbre is a tall tree; un gros arbre is a thick one.',
    watch: 'Say gros about a person and it is about weight, so choose carefully.',
    ask: { prompt: 'Which one describes a tall person?', answer: 'grand', with: ['gros', 'petit', 'jeune'] } },
  { id: 'ancien', kind: 'false friend', words: ['ancien', 'vieux', 'dernier', 'premier'],
    title: 'Ancien before and after the noun',
    plain: 'Before a noun, ancien means “former”: mon ancien patron, my former boss. After a noun it means “ancient” or “old”: une ville ancienne. Vieux is “old” in the everyday sense.',
    watch: 'The same adjective, two meanings, decided by where it sits.',
    ask: { prompt: 'Which one means “former” (as in “my former boss”)?', answer: 'ancien', with: ['vieux', 'dernier', 'premier'] } },
  { id: 'formidable', kind: 'false friend', words: ['formidable', 'dangereux', 'difficile', 'important'],
    title: 'Formidable is “great”',
    plain: 'Formidable means fantastic or tremendous. It has lost the sense of “fearsome” that English “formidable” keeps.',
    watch: 'C’est formidable! is a compliment.',
    ask: { prompt: 'Which one means “fantastic”?', answer: 'formidable', with: ['dangereux', 'difficile', 'important'] } },
  { id: 'eventuel', kind: 'false friend', words: ['éventuel', 'sûr', 'certain', 'important'],
    title: 'Éventuel is “possible”',
    plain: 'Éventuel means possible or potential: une éventuelle erreur, a possible mistake. It does not mean “eventual”: for that, French says final.',
    watch: 'The adverb éventuellement means “possibly”. Wiktionary marks the sense “eventually” as Québec usage, so you will hear it both ways; “eventually” in France is finalement or un jour.',
    ask: { prompt: 'Which one means “possible, potential”?', answer: 'éventuel', with: ['sûr', 'certain', 'important'] } },
  { id: 'savoir-connaitre', kind: 'near-synonyms', words: ['savoir', 'connaître', 'comprendre', 'apprendre'],
    title: 'Savoir and connaître',
    plain: 'Both are “to know”. Savoir is to know a fact or a skill: je sais nager, je sais où il habite. Connaître is to be acquainted with a person, a place, a work: je connais Marie, je connais Montréal.',
    watch: 'English uses one word for both, which is why this is one of the last things to settle.',
    ask: { prompt: 'Which one means “to know a person or a place”?', answer: 'connaître', with: ['savoir', 'comprendre', 'apprendre'] },
    cues: { savoir: 'to know a fact', connaître: 'to know a person or place' } },
  { id: 'porter', kind: 'near-synonyms', words: ['apporter', 'amener', 'emmener', 'emporter'],
    title: 'Bring and take: four words',
    plain: 'French splits “bring” and “take” by whether it is a thing or a person, and which way it is going. Apporter: bring a thing here. Amener: bring a person here. Emporter: take a thing away. Emmener: take a person away.',
    watch: 'The prefix gives it away: em- and en- mean away from here, a- means towards.',
    ask: { prompt: 'Which one means “to bring a thing here”?', answer: 'apporter', with: ['amener', 'emporter', 'emmener'] },
    cues: { apporter: 'bring a thing', amener: 'bring a person', emporter: 'take a thing away', emmener: 'take a person away' } },
  { id: 'quitter', kind: 'near-synonyms', words: ['quitter', 'partir', 'laisser', 'sortir'],
    title: 'Four ways to leave',
    plain: 'Quitter takes an object: you quit a place or a person. Partir does not: je pars, I am leaving. Laisser is to leave something behind. Sortir is to go out.',
    watch: 'Je quitte Montréal and je pars de Montréal are both right; je pars Montréal is not.',
    ask: { prompt: 'Which one takes a direct object: “to leave (a place or a person)”?', answer: 'quitter', with: ['partir', 'sortir', 'rester'] },
    cues: { quitter: 'to leave a place or person', partir: 'to leave, to set off', laisser: 'to leave behind', sortir: 'to go out' } },
  { id: 'ecouter', kind: 'near-synonyms', words: ['écouter', 'entendre', 'regarder', 'voir'],
    title: 'Hear and listen, see and look',
    plain: 'Entendre is to hear, which just happens. Écouter is to listen, which you do on purpose. Voir is to see; regarder is to look at, or to watch.',
    watch: 'In Canadian French, écouter is also used for watching television: écouter un film.',
    ask: { prompt: 'Which one means “to listen (on purpose)”?', answer: 'écouter', with: ['entendre', 'regarder', 'voir'] },
    cues: { écouter: 'to listen on purpose', entendre: 'to hear without trying' } },
  { id: 'rentrer', kind: 'near-synonyms', words: ['rentrer', 'retourner', 'revenir', 'rester'],
    title: 'Going back',
    plain: 'Rentrer is to go home, or back in. Retourner is to go back to a place. Revenir is to come back to where the speaker is.',
    watch: 'Je rentre means “I am heading home”.',
    ask: { prompt: 'Which one means “to go back home”?', answer: 'rentrer', with: ['retourner', 'revenir', 'rester'] },
    cues: { rentrer: 'to go home', retourner: 'to go back there', revenir: 'to come back here' } },
  { id: 'blesser', kind: 'false friend', words: ['blesser'],
    title: 'Blesser is “to wound”',
    plain: 'Blesser is to wound or injure; je suis blessé means I am hurt. It has nothing to do with blessing, which is bénir.',
    watch: 'It also covers hurting someone’s feelings.' },
  { id: 'sympathique', kind: 'false friend', words: ['sympathique'],
    title: 'Sympathique is “nice”',
    plain: 'Sympathique describes someone friendly and likeable: elle est très sympathique. It is not “sympathetic” in the sense of feeling for someone’s trouble.',
    watch: 'In speech it shrinks to sympa.' },
  { id: 'jour-journee', kind: 'near-synonyms', words: ['jour', 'journée', 'an', 'année', 'matin', 'matinée', 'soir', 'soirée'],
    title: 'Jour and journée, an and année',
    plain: 'The short forms — jour, an, matin, soir — name a point or a unit: bonjour, deux ans, ce matin. The long forms — journée, année, matinée, soirée — name the span, with what happens in it: bonne journée, toute l’année, une soirée entre amis.',
    watch: 'Bonne journée, not bon jour, as you leave a shop.' },
];
