// Jasette — what changed, newest first. Shown on the About screen.
export default [
  { v: '1.6.1', date: '2026-10-08', what: 'Correction importante : la première fois qu’une question te fait parler, après avoir répondu « Oui, écoute-moi », le résultat et le bouton pour continuer n’apparaissaient plus, donc on restait bloqué (même avec une bonne réponse). C’est réparé, et un test refait tout le parcours.' },
  { v: '1.6.0', date: '2026-10-07', what: 'Nouvelles questions « Laquelle est correcte ? » : 320 phrases de la Banque de dépannage linguistique de l’Office québécois de la langue française (données ouvertes), avec la bonne phrase et les deux fautives les plus proches, puis un lien vers la règle de l’OQLF.' },
  { v: '1.5.0', date: '2026-10-07', what: 'Conversations : cinq échanges dans des situations de la vie courante au Québec, où tu entends, tu réponds (en touchant ou à voix haute) et tu vois pourquoi. Nouveaux types de questions : associer cinq mots à leur sens, et « Laquelle est fausse ? » (repérer l’erreur) pour les formes de conjugaison que tu connais déjà. Culture : quatorze courtes notes sur les différences entre le français du Québec, du Canada et de France, et sur le joual, chacune avec ses sources.' },
  { v: '1.4.0', date: '2026-10-07', what: 'Parler : une série où une voix dit la phrase et, dès que l’enregistrement finit, le téléphone t’écoute et marque les mots. Conjugaison : deux questions par série qui montrent la forme d’ensemble — tout un temps (je, tu, il, nous, vous, ils) et une personne à travers les temps. Quand la lecture à voix haute est active et que tu te trompes, la bonne réponse est lue en français.' },
  { v: '1.3.0', date: '2026-10-07', what: 'Questions où tu parles : « Écoute et répète » (un vrai enregistrement, puis toi) et « Dis-le en français » (tu vois l’anglais, tu dis la phrase). Le téléphone peut maintenant t’écouter : il montre ce qu’il entend pendant que tu parles, puis marque la phrase mot par mot et souligne ceux qu’il n’a pas saisis. Il te le demande une seule fois, car ta voix est envoyée au fabricant du navigateur.' },
  { v: '1.2.0', date: '2026-10-07', what: 'On t’explique avant de te tester : une carte pour chaque nouveau mot (sens, son, exemples, et pour un verbe son présent et la forme de chaque exemple), une leçon pour chaque étape de Conjugaison qui s’appuie sur les précédentes, et des expressions comme « avoir du bol » expliquées. Les séries font maintenant environ 18 questions ; jusqu’à 40 nouveautés par jour si tu fais plusieurs séries.' },
  { v: '1.1.0', date: '2026-10-06', what: 'Conjugaison : une section à part pour les verbes (les douze essentiels d’abord, puis plus de verbes et plus de temps, seize étapes). Lecture à voix haute : un haut-parleur à côté de chaque choix, un bouton « Lire » sur chaque question et une lecture automatique. Plus d’anglais dans les instructions du test de niveau.' },
  { v: '1.0.0', date: '2026-10-06', what: 'Première version : 7 000 mots en huit étapes, voix du Québec et de France, la piste « Québec », des phrases à remplir en touchant les mots, et un test de niveau pour ne pas repasser ce que tu sais déjà.' },
];
